- hosts: gateway
  serial: 1
  tasks:

    - name: install pip
      become: yes  
      package:
        name: python2-pip
        state: present


    - name: install docker-py
      become: yes  
      pip:
        name: [ docker ]
        

    - name: stop old release
      become: yes  
      docker_container: 
         name: "{{ SERVICE_NAME }}"
         state: stopped

    - name: delete old release
      become: yes  
      docker_container: 
         name: "{{ SERVICE_NAME }}"
         state: absent

    - name: '[DOCKER] Create docker network'
      docker_network:
        name: "service-network"
        

    - name: "Registry login"
      docker_login:
        registry: "{{ REGISTRY }}"
        username: "{{ REGISTRY_USER }}"
        password: "{{ REGISTRY_PASSWORD }}"

    - name: 'Create new release'
      docker_container:
        name: "{{ SERVICE_NAME }}"
        recreate: true
        restart_policy: unless-stopped
        state: started
        pull: yes
        image: '{{RELEASE_IMAGE}}'
        published_ports:
          - '9000:9000'
          
        networks: 
          - name: "service-network"
        purge_networks: yes


    - name: 'postgres container'
      docker_container:
        name: 'postgres'
        restart_policy: unless-stopped
        state: started
        recreate: no
        image: "{{ POSTGRES }}"
        published_ports:
          - '5432:5432'
        networks: 
          - name: "service-network"
      when: POSTGRES is defined

    - name: 'NGINX container restart with pull'
      become: yes  
      docker_container:
        name: 'nginx'
        restart_policy: unless-stopped
        state: started
        pull: yes
        image: '{{NGINX_IMAGE}}' 
        published_ports:
          - '80:80'
          - '443:443'
        networks: 
          - name: "service-network"
        purge_networks: yes

# remove old containers and volumes
    - name: Removing exited containers
      shell: docker ps -a -q -f status=exited | xargs --no-run-if-empty docker rm --volumes

    - name: Removing untagged images
      shell: docker images | awk '/^<none>/ { print $3 }' | xargs --no-run-if-empty docker rmi -f

    - name: Removing volume directories
      shell: docker volume ls -q --filter="dangling=true" | xargs --no-run-if-empty docker volume rm
